# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_BfrWyqngYYsVasBCIaxyxXqEvi8lL-

ASSIGNMENT-22

Q1)
"""

import seaborn as sns
import plotly.express as px

titanic = sns.load_dataset("titanic")
fig = px.scatter(titanic, x="age", y="fare")
fig.show()

"""Q2)"""

import plotly.express as px

# Load the "tips" dataset from Plotly Express
tips = px.data.tips()

# Create a box plot using Plotly Express
box_plot = px.box(tips, x="day", y="total_bill", title="Box Plot of Total Bill by Day")

# Show the plot
box_plot.show()



"""Q3)"""

import plotly.express as px

tips = px.data.tips()
fig = px.histogram(tips, x="sex", y="total_bill", color="smoker", pattern_shape="smoker", facet_col="day")
fig.show()

"""Q4)"""

import plotly.express as px

iris = px.data.iris()
fig = px.scatter_matrix(iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species", title="Scatter matrix of iris data set")
fig.show()

"""Q5)Distplot is a function in the seaborn library that plots a histogram with a line on top of it. The line is a kernel density estimate (KDE) of the distribution. It is used to visualize the distribution of a univariate set of observations."""

import plotly.express as px

tips = px.data.tips()
fig = px.histogram(tips, x="total_bill", y="tip", color="sex", marginal="rug")
fig.show()